name: some test
on:
  push:
jobs:
  fn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - name: install npm
        run: |
          npm install
      - uses: phips28/gh-action-bump-version@v9
        with:
          version-type: patch
      
  
    
