name: some test
on:
  push:
jobs:
  fn:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: actions/checkout@v3.5.2
      - name: install npm
        run: |
          npm install
      - uses: phips28/gh-action-bump-version@v9.1.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          version-type: patch
      
  
    
